image: mapret/cmake-qt5:latest

stages:
  - build

build:
  stage: build
  script:
   - mkdir build && cd build
   - cmake -DCMAKE_BUILD_TYPE=MinSizeRel ..
   - cmake --build .
  artifacts:
    paths:
     - build/modelviewer
