image: mapret/cppimage:v1

stages:
  - build

build:
  stage: build
  script:
   - apk add qt5-qtbase-dev
   - mkdir build && cd build
   - cmake -DCMAKE_BUILD_TYPE=MinSizeRel ..
   - cmake --build .
  artifacts:
    paths:
     - build/modelviewer
